### ISSUE TITLE
Ammo doesn't update with swapping weapons

### ISSUE THREAD

**Issue by Galaxy25** [TigardHighGDC/Augmentation#122]
When using the inventory system the inventory doesn't update the current ammo causing weapons to have more ammo then there limit. This can be fixed by adding another list to keep track of the current ammo for each weapon

**Comment by BrandonPacewic** [comment]
@Galaxy25 I'll add this to my backlog list to take care of this week.

**Comment by BrandonPacewic** [comment]
Blocked by #126.
