### ISSUE TITLE
Weapon Inventory System

### ISSUE THREAD

**Issue by Galaxy25** [TigardHighGDC/Augmentation#14]
Create an inventory system that can be updated with new guns stored as a list. Give a max size to limit the amount of weapons that can be picked up and a dropping mechanic to remove old weapons. Let the player be able to change weapons by either scrolling with a mouse or using keys. I'm not sure which keys are commonly used.

**Comment by BrandonPacewic** [comment]
@Galaxy25 Moving this to the `Game Design` milestone. Let me know if you disagree with my thinking. 

- Issues for features are `Game Design`
- Prs for those features are `Programming`
- Issues for bugs are `Programming`

**Comment by Galaxy25** [comment]
I would consider it a core gameplay feature because a lot of other game objects and scripts would rely on it.

**Comment by BrandonPacewic** [comment]
> I would consider it a core gameplay feature because a lot of other game objects and scripts would rely on it.

I also consider it to be a core gameplay feature. My point with the milestones that I have set up is that they fall under the OGPC Achievement Guide sections.

**Comment by BrandonPacewic** [comment]
@Galaxy25 Can I ask for a few pieces of information?

1. What is the max number of weapons the player can hold vs how many are we going to have?
2. Will the player need to drop weapons to acquire new ones?

**Comment by Galaxy25** [comment]
1. Have a variable that can set the size
2.  If the player reaches max inventory

**Comment by BrandonPacewic** [comment]
> @BrandonPacewic
> 
> 1. Have a variable that can set the max size
> 2. If the player reaches max inventory

Roger that.
