### ISSUE TITLE
Extend the procedural level map into a mini-map

### ISSUE THREAD

**Issue by BrandonPacewic** [TigardHighGDC/Augmentation#142]
We need a small map to show the player during gameplay. Pretty sure I can modify the existing code to accomplish it.

**Comment by Galaxy25** [comment]
@BrandonPacewic We could also have the player move to the map when they exit the room and then select the next room they want to move to

**Comment by BrandonPacewic** [comment]
> We could also have the player move to the map when they exit the room and then select the next room they want to move to

That is exactly what I am planning at the moment.

**Comment by BrandonPacewic** [comment]
No longer a priority.
