### ISSUE TITLE
A* AI Algorithmns

### ISSUE THREAD

**Issue by Galaxy25** [TigardHighGDC/Augmentation#19]
Unity 2D doesn't have any inbuilt pathfinding within the game engine. [A*](https://arongranberg.com/astar/) provides 2d algorithms to provide object avoidance while following the player. All Unity tutorials I found were based on this library. Before using it I want to get approval before using a 3rd party library and find out what licensing it requires.

**Comment by BrandonPacewic** [comment]
It appears that there licensing allows for use in commercial projects. This includes the free version. For this reason I believe that it is ok for us to use it as everyone in the competition will have equal access to it.

**Comment by Galaxy25** [comment]
Can you post the link?

**Comment by BrandonPacewic** [comment]
They have [this](https://arongranberg.com/astar/docs/faq.html) in their FAQ. Currently trying to track down the exact use license.

**Comment by Galaxy25** [comment]
I might have found a way to get Unity NavMeshes to work in 2D

**Comment by BrandonPacewic** [comment]
They follow the Unity asset store public use license so we should be good to use it.

**Comment by Galaxy25** [comment]
Ok, cool the way to use unity natively didn't work.

**Comment by Galaxy25** [comment]
Also found this on the `README.MD` stating `The license is the AssetStore Free License and the AssetStore Commercial License respectively for the Free and Pro versions of the project.`
