### ISSUE TITLE
Unique Scriptable Items

### ISSUE THREAD

**Issue by Galaxy25** [TigardHighGDC/Augmentation#26]
Find out how to use multiple-item scripts controlled by a singular script and how to trigger multiple scripts without interfering with each other. For example, creating a unique weapon such as gaining health when hitting an enemy and losing when missing. Then implant when we have it figured out.

**Comment by BrandonPacewic** [comment]
Planning on doing this with a list of functions to call per every gun object update using `Action`s. I'll look into it more.

**Comment by Galaxy25** [comment]
I didn't know about `Action`. I'll also look a little into it

**Comment by Galaxy25** [comment]
This seems to be interesting https://www.reddit.com/r/gamedev/comments/hbporz/how_does_item_interaction_works_in_games_like_the/

**Comment by BrandonPacewic** [comment]
Please see [this]() commit for my initial idea for this problem.

Essentially we will now be able to give weapons and bullets more complex effects on item pickups.

For example, if we wanted to add an effect to the gun that would heal the player every time they shot we could set up the powerup like this:

```cs
private void OnTriggerEnter2D(Collider2D collision)
    {
        if (collision.gameObject.tag == "Player")
        {
            collision.gameObject.GetComponent<Data>().weaponEffects.Add(() => {
                GetComponentInParent<PlayerHealth>().Health += 1;
            });
        }
    }
```

This `Action` function will be called every time the player shoots a individual bullet. We can continue to expand this to add an infinite number of effects. This same `Action` system has also been added to bullets. So for instance if we want to add an explosion we could do that with:

```cs
bulletEffects.Add() => {
...
});
```

I don't actually know how to make an explosion but you get the idea.

**Comment by BrandonPacewic** [comment]
Similarly, this concept can be expanded to abilities. Instead of having a new script per ability we have an `Action` that we change in and out with different functions.

**Comment by Galaxy25** [comment]
@BrandonPacewic I haven't made the draft yet but I'm planning on using C# `event`. I think it would make the item effects more modular and efficient. I also looked into `UnityEvent`. The difference of `UnityEvent` seems to be lower efficiency and the ability to drag and drop, and do other things with the editor. I know how disappointed you are about not using the unity editor but I think `event`s are better.  Even tutorials made by Unity used `event`.

**Comment by BrandonPacewic** [comment]
> @BrandonPacewic I haven't made the draft yet but I'm planning on using C# `event`. I think it would make the item effects more modular and efficient. I also looked into `UnityEvent`. The difference of `UnityEvent` seems to be lower efficiency and the ability to drag and drop, and do other things with the editor. I know how disappointed you are about not using the unity editor but I think `event`s are better. Even tutorials made by Unity used `event`.

However you want to do it is ok with me. I find the idea of using just pure C# more appealing than using more of the unity editor but if you feel strongly about doing it this way go ahead. One less thing for me to do. 🙃
