### ISSUE TITLE
Sprint #3 Peoples got sick :(

### ISSUE THREAD

**Issue by BrandonPacewic** [TigardHighGDC/Augmentation#48]
We did so so last sprint. Now we really need to focus on what we are stuck on... Room Design.

Here are the goals for the next two weeks:

- **Room & Level Design**
- Async Scene Loading #15.
- #22.
- Changelog
- Some* basic enemies
  - #39 
  - #40 

We really need to get a specific layout for our rooms this includes:
- Tiling
- Land marks
- More stuff
- Player interactable items
- Enemy placement

Let me know if anyone needs anything! Other than that let's get this done!

**Comment by BrandonPacewic** [comment]
@Galaxy25 Because I am taking a break this week I am going to extend this sprint to `2/6` if that sounds good to you.

**Comment by Galaxy25** [comment]
@BrandonPacewic Get some rest you need it. The sprint definitely needed an extension

**Comment by BrandonPacewic** [comment]
Sprint 4 is up! #86.
