### ISSUE TITLE
Bullet damage should be controlled by `WeaponData`

### ISSUE THREAD

**Issue by BrandonPacewic** [TigardHighGDC/Augmentation#55]

**Comment by Galaxy25** [comment]
The bullet has access to all of the variables in `WeaponData`

**Comment by BrandonPacewic** [comment]
> The bullet has access to all of the variables in `WeaponData`

Yes however, at least from my understanding, damage is not controlled there. Or am I misunderstanding how it works?

**Comment by Galaxy25** [comment]
I took a look it isn't being controlled by `WeaponData`. However, it should be; a bug-fix request?
