### ISSUE TITLE
Create a script similar to AIPath 

### ISSUE THREAD

**Issue by Galaxy25** [TigardHighGDC/Augmentation#79]
Create a script similar to A* but move using rigidbody2d.
https://www.youtube.com/watch?v=jvtFUfJ6CP8

**Comment by BrandonPacewic** [comment]
Do you want a whole new script or do you want me to edit our already existing enemies to use this system?

**Comment by Galaxy25** [comment]
I thinking of a way to do this. Either using rigid body velocity makes it moves expectedly but it doesn't allow for forces since forces edit the velocity. But with `AddForces` the movement isn't tight. So I'm thinking of creating a type of braking system to allow the enemies to slow down faster than speeding up
