### ISSUE TITLE
Digital Art for Enemies

### ISSUE THREAD

**Issue by BrandonPacewic** [TigardHighGDC/Augmentation#82]
Basically just an expanse of what we currently have for enemies. Different images, frames, weapon attacks, new enemies. More and more art.

**Comment by Galaxy25** [comment]
I'm changing this to specifically be art and make issues for specific enemies

**Comment by BrandonPacewic** [comment]
> I'm changing this to specifically be art and make issues for specific enemies

Makes sense.

**Comment by BrandonPacewic** [comment]
I believe that we have all the art for enemies done.
